description: Apps and Engines when launching with a project only context.
engines:
  tk-desktop:
    apps:
      tk-multi-imagepublish-footage:
        app_mode: gui
        hook_publish: default
        hook_scan_scene: default
        location: {path: 'https://github.com/AardmanCGI/tk-multi-imagepublish.git', type: git,
          version: v0.4.5}
        menu_name: ImagePublish Footage
        publish_type: footage
        tank_type: Footage Sequence
        target_default_name: master
        title_name: Image Publishing - Footage
        version_number_padding: 3
      tk-multi-imagepublish-output:
        app_mode: gui
        hook_publish: default
        hook_scan_scene: default
        location: {path: 'https://github.com/AardmanCGI/tk-multi-imagepublish.git', type: git,
          version: v0.4.5}
        menu_name: ImagePublish Output
        publish_type: output
        tank_type: Output Sequence
        target_default_name: master
        title_name: Image Publishing - Output
        version_number_padding: 3
      tk-multi-imagepublish-render:
        app_mode: gui
        hook_publish: default
        hook_scan_scene: default
        location: {path: 'https://github.com/AardmanCGI/tk-multi-imagepublish.git', type: git,
          version: v0.4.5}
        menu_name: ImagePublish Render
        publish_type: render
        tank_type: Render Sequence
        target_default_name: master
        title_name: Image Publishing - Render
        version_number_padding: 3
      tk-multi-launchmari: '@launch_mari'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchnukestudio: '@launch_nukestudio'
      tk-multi-launchnukex: '@launch_nukex'
      tk-multi-launchpftrack: '@launch_pftrack'
      tk-multi-launchphotoshop: '@launch_photoshop'
      tk-multi-launchrv: '@launch_rv'
      tk-multi-launchtopogun: '@launch_topogun'
      tk-multi-launchzbrush: '@launch_zbrush'
    collapse_rules:
    - {button_label: $app, match: Launch $app, menu_label: None}
    - {button_label: ImagePublish, match: ImagePublish $type, menu_label: $type}
    debug_logging: false
    default_group: Studio
    groups:
    - matches: ['*Hiero*', '*Houdini*', '*Mari*', '*Max*', '*Maya*', '*Motion*', '*Nuke*',
        '*Photoshop*', '*Softimage*', '*ZBrush*', '*PFTrack*', '*TopoGun*']
      name: Creative Tools
    hook_launch_python: default
    location: {name: tk-desktop, type: app_store, version: v2.0.5}
    show_recents: true
  tk-mari:
    apps:
      tk-multi-about: '@about'
      tk-multi-workfiles:
        allow_task_creation: true
        file_extensions: []
        hook_copy_file: default
        hook_filter_publishes: default
        hook_filter_work_files: default
        hook_scene_operation: default
        launch_at_startup: false
        launch_change_work_area_at_startup: false
        location: {name: tk-multi-workfiles, type: app_store, version: v0.6.15}
        saveas_default_name: scene
        saveas_prefer_version_up: false
        sg_entity_type_extra_display_fields: {}
        sg_entity_type_filters: {}
        sg_entity_types: [Asset]
        sg_task_filters: []
        task_extra_display_fields: []
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
        version_compare_ignore_fields: []
    compatibility_dialog_min_version: 2
    debug_logging: false
    location: {name: tk-mari, type: app_store, version: v1.0.2}
  tk-maya:
    apps:
      tk-multi-about: '@about'
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-workfiles: '@workfiles-launch-at-startup'
      tk-multi-workfiles2:
        allow_task_creation: true
        custom_actions_hook: '{self}/custom_actions.py'
        entities:
        - caption: Assets
          entity_type: Task
          filters:
          - [entity, type_is, Asset]
          hierarchy: [entity.Asset.sg_asset_type, entity, step, content]
        - caption: Shots
          entity_type: Task
          filters:
          - [entity, type_is, Shot]
          hierarchy: [entity.Shot.sg_sequence, entity, step, content]
        file_extensions: []
        hook_copy_file: '{self}/copy_file.py'
        hook_filter_publishes: '{self}/filter_publishes.py'
        hook_filter_work_files: '{self}/filter_work_files.py'
        hook_scene_operation: '{self}/scene_operation_tk-maya.py'
        launch_at_startup: false
        location: {name: tk-multi-workfiles2, type: app_store, version: v0.7.9}
        my_tasks_extra_display_fields: []
        saveas_default_name: scene
        saveas_prefer_version_up: false
        show_my_tasks: true
        template_publish: null
        template_publish_area: null
        template_work: null
        template_work_area: null
        version_compare_ignore_fields: []
    compatibility_dialog_min_version: 2015
    debug_logging: false
    location: {name: tk-maya, type: app_store, version: v0.5.1}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    template_project: null
    use_sgtk_as_menu_name: false
  tk-nuke:
    apps: {tk-multi-about: '@about', tk-multi-screeningroom: '@launch_screeningroom',
      tk-multi-workfiles: '@workfiles-launch-at-startup-nuke'}
    compatibility_dialog_min_version: 10
    debug_logging: false
    favourite_directories: []
    location: {name: tk-nuke, type: app_store, version: v0.3.1}
    menu_favourites:
    - {app_instance: tk-multi-workfiles, name: Shotgun File Manager...}
    project_favourite_name: Shotgun Current Project
    use_sgtk_as_menu_name: false
  tk-photoshop:
    apps: {tk-multi-about: '@about', tk-multi-screeningroom: '@launch_screeningroom',
      tk-multi-workfiles: '@workfiles'}
    debug_logging: false
    location: {name: tk-photoshop, type: app_store, version: v0.3.2}
  tk-shell:
    apps:
      tk-multi-imagepublish-batch:
        app_mode: batch
        hook_publish: default
        hook_scan_scene: default
        location: {path: 'https://github.com/AardmanCGI/tk-multi-imagepublish.git', type: git,
          version: v0.4.5}
        menu_name: default
        publish_type: default
        tank_type: default
        target_default_name: master
        title_name: default
        version_number_padding: 3
      tk-multi-imagepublish-footage:
        app_mode: gui
        hook_publish: default
        hook_scan_scene: default
        location: {path: 'https://github.com/AardmanCGI/tk-multi-imagepublish.git', type: git,
          version: v0.4.5}
        menu_name: footage
        publish_type: footage
        tank_type: Footage Sequence
        target_default_name: master
        title_name: Image Publishing - Footage
        version_number_padding: 3
      tk-multi-imagepublish-output:
        app_mode: gui
        hook_publish: default
        hook_scan_scene: default
        location: {path: 'https://github.com/AardmanCGI/tk-multi-imagepublish.git', type: git,
          version: v0.4.5}
        menu_name: output
        publish_type: output
        tank_type: Output Sequence
        target_default_name: master
        title_name: Image Publishing - Output
        version_number_padding: 3
      tk-multi-imagepublish-render:
        app_mode: gui
        hook_publish: default
        hook_scan_scene: default
        location: {path: 'https://github.com/AardmanCGI/tk-multi-imagepublish.git', type: git,
          version: v0.4.5}
        menu_name: render
        publish_type: render
        tank_type: Render Sequence
        target_default_name: master
        title_name: Image Publishing - Render
        version_number_padding: 3
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchnuke: '@launch_nuke'
      tk-multi-launchnukex: '@launch_nukex'
      tk-multi-launchpftrack: '@launch_pftrack'
      tk-multi-launchphotoshop: '@launch_photoshop'
      tk-multi-launchrv: '@launch_rv'
      tk-multi-launchzbrush: '@launch_zbrush'
    debug_logging: false
    location: {name: tk-shell, type: app_store, version: v0.4.1}
frameworks:
  tk-framework-aapublish_v0.0.x:
    location: {path: 'https://github.com/AardmanCGI/tk-framework-aapublish.git', type: git,
      version: v0.0.3}
    hook_publish: default
  tk-framework-aapublish_v0.1.x:
    location: {path: 'https://github.com/AardmanCGI/tk-framework-aapublish.git', type: git,
      version: v0.1.1}
    hook_publish: default
  tk-framework-adminui_v0.x.x:
    location: {name: tk-framework-adminui, type: app_store, version: v0.1.2}
  tk-framework-login_v1.x.x:
    location: {name: tk-framework-login, type: app_store, version: v1.2.1}
  tk-framework-qtwidgets_v2.x.x:
    location: {name: tk-framework-qtwidgets, type: app_store, version: v2.0.6}
  tk-framework-shotgunutils_v3.x.x:
    location: {name: tk-framework-shotgunutils, type: app_store, version: v3.0.4}
  tk-framework-softimageqt_v1.0.1:
    location: {name: tk-framework-softimageqt, type: app_store, version: v1.0.1}
  tk-framework-widget_v0.1.16:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.16}
  tk-framework-widget_v0.1.18:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.18}
  tk-framework-widget_v0.1.19:
    location: {name: tk-framework-widget, type: app_store, version: v0.1.19}
includes: [./includes/app_launchers.yml, ./includes/common_apps.yml]
